### ISSUE TITLE
🪲 Bug Report - Start-WARACollector does not work correctly if specify only TenantID

### ISSUE THREAD

**Issue by tksh164** [Azure/Well-Architected-Reliability-Assessment#51]
## Describe the bug

Start-WARACollector does not work correctly if specify only `-TenantID` to it. The `$Scope_SubscriptionIds` initialized as an empty array if subscription ID were not specified. So, the replace method cannot call.

https://github.com/Azure/Well-Architected-Reliability-Assessment/blob/e8f8120eeb95feabab1014b767f38de50c6364d7/src/modules/wara/wara.psm1#L79

```powershell
$Scope_SubscriptionIds.replace('/subscriptions/', '')
$Scope_ImplicitSubscriptionIds.replace('/subscriptions/', '')
```

## To Reproduce

1. Run Start-WARACollector without `-SubscriptionIds` parameter.

## Expected behavior

Start-WARACollector does work correctly even if specify only `-TenantID`.

## Screenshots 📷

![Image](https://github.com/user-attachments/assets/6ebcef16-d603-444e-917d-52ea1fd4161d)

## Additional context

n/a

**Comment by kpoineal** [comment]
@tksh164 Thank you! I'll get this fixed today. We shouldn't be able to run the script without some type of scope below the level of tenantid. Great catch!
