### ISSUE TITLE
🪲 Bug Report - Invoke-WAFQuery have not have UseTenantScope switch

### ISSUE THREAD

**Issue by tksh164** [Azure/Well-Architected-Reliability-Assessment#52]
## Describe the bug

Get-WAFResourceType will call Invoke-WAFQuery with `-UseTenantScope` switch if `$SubscriptionIds` is an empty array. But, Invoke-WAFQuery have not have the `-UseTenantScope` switch.

https://github.com/Azure/Well-Architected-Reliability-Assessment/blob/e8f8120eeb95feabab1014b767f38de50c6364d7/src/modules/wara/collector/collector.psm1#L224

## To Reproduce

n/a

## Expected behavior

It is enough to just call Invoke-WAFQuery with an empty array. If to do so, Invoke-WAFQuery will use `-UseTenantScope` switch on Search-AzGraph.

https://github.com/Azure/Well-Architected-Reliability-Assessment/blob/e8f8120eeb95feabab1014b767f38de50c6364d7/src/modules/wara/utils/utils.psm1#L12

## Screenshots 📷

n/a

## Additional context

n/a

**Comment by kpoineal** [comment]
Do we want the -usetenantscope flag for the default behavior if no query is provided?

**Comment by tksh164** [comment]
> Do we want the -usetenantscope flag for the default behavior if no query is provided?

I'm guessing you talk about subscription IDs because `$Query` always has a query as a default value.

https://github.com/Azure/Well-Architected-Reliability-Assessment/blob/e8f8120eeb95feabab1014b767f38de50c6364d7/src/modules/wara/utils/utils.psm1#L1-L12

About `$SubscriptionIds`, I don't think need `-usetenantscope` flag for **Invoke-WAFQuery** because we can pass an empty array to `$SubscriptionIds`. An empty array indicate that we should use `-UseTenantScope` switch with **Search-AzGraph**.

Like following:

```powershell
function Get-WAFResourceType {
    [CmdletBinding()]
    param (
        [Parameter(Mandatory = $true)]
        [AllowEmptyCollection()]
        [string[]] $SubscriptionIds
    )

    $q = "Resources
| summarize count() by type
| project type"

    # It is enough to just call Invoke-WAFQuery.
    $r = $SubscriptionIds ? (Invoke-WAFQuery -Query $q -SubscriptionIds $SubscriptionIds) : (Invoke-WAFQuery -Query $q)

    return $r
}
```

I will fix this.
